### ISSUE TITLE
no gmft/formatters folder in new 0.3.0 release

### ISSUE THREAD

**Issue by Datata1** [conjuncts/gmft#23]
Hello,

i installed the new 0.3.0 version of gmft and it seems that the formatters folder is missing in the installation. Without this folder i cannot import the formatters with `gmft.auto` .

This is the picture of the downloaded tar.gz from pypi: 
![image](https://github.com/user-attachments/assets/62572e9c-d341-45bc-8a07-0b30bcd5b694)

**Comment by Datata1** [comment]
@conjuncts 

first of all, this repo is really cool and i am looking forward to see this library grow :)

it is off-topic to this issue, but are there some examples of using the ocr implementation (img2table formatter and detector stuff)? I could read the source code and try to implement it myself, but i was wondering  if there is already an example.

**Comment by conjuncts** [comment]
Thank you! The img2table stuff is brand new and I will be writing documentation soon :tm:. Whenever I finish they will available at gmft.readthedocs.org and I will also let you know. 

I tried the new build with colab and it seems to be working, let me know if this is not the case.

**Comment by Datata1** [comment]
Okay, thank you, I appreciate it! 👍

**Comment by conjuncts** [comment]
Okay, docs are finished. The relevant pages are [RAG](https://gmft.readthedocs.io/en/latest/rag.html) and [img2table](https://gmft.readthedocs.io/en/latest/detectors/img2table.html). 

But I realize I may have misinterpreted your comment, sorry! Indeed the img2table code mentions OCR, but the new img2table stuff is unfortunately not actually related to OCR. In fact, I'm not sure I'll ever get to supporting OCR unfortunately.

With OCR, quality increases at the expense of longer runtime. At that time scale, there are already many great tools out there tools like [surya](https://github.com/VikParuchuri/surya), [marker](https://github.com/VikParuchuri/marker), [nougat](https://github.com/facebookresearch/nougat). Sadly, I think gmft would be better focused on extracting tables relatively quickly (~1 sec per page) rather than compete with existing options that already have OCR.
