### ISSUE TITLE
Interested in adding new table model?

### ISSUE THREAD

**Issue by VikParuchuri** [conjuncts/gmft#27]
Great work with gmft!  I just trained a new table model here - https://github.com/VikParuchuri/surya .

Ping me if you're interested in integration.  Happy to discuss.

**Comment by conjuncts** [comment]
I am in turn a huge fan of surya! I've been following the table detection update with great interest. I'll be sending out an email shortly. In summary, I'm very supportive of the idea.

**Comment by conjuncts** [comment]
Okay, with b759c7b I've got a [notebook up](https://github.com/conjuncts/gmft/blob/main/notebooks/example_tabled_compat.ipynb) demonstrating Tabled's structure recognition with Table Transformer's detection. This combination in particular is pretty nice, because Tabled's bottleneck is table detection, while TATR's bottleneck is TSR. Surya's detection I still need to support.
