### ISSUE TITLE
General questions and parameter tweaking

### ISSUE THREAD

**Issue by snexus** [conjuncts/gmft#6]
Hi,

Thank you for the project, it is really promising. The speed and quality are great, in general. 
I would like to integrate it with my RAG system, so have been playing a bit with this library trying to parse different research papers and financial reports.

A couple of questions:

- Is there a sensible threshold to rule out false positives? E.g. in many cases document index or list of authors are detected as a table, with confidence level above 0.9. Is there a way to filter it out?
- In some cases, the library complains about boxes overlap and can't parse the table - does it makes sense to increase the overlap threshold and try to re-parse?
- In many tables, there is a title below or above the table, which captures meaningful context about the table (for example when using in RAG systems). Is there an easy way to detect this title (I understand that technically it isn't part of the table).
- In general, what are most useful parameters to tweak in order to fine-tune the process for a specific documents.

Thanks

**Comment by conjuncts** [comment]
Thank you for trying out my project!

1. I've noticed this as well. I've been using a not-very-elegant method of measuring the percentage of content with numerical values, then rejecting if there is not enough numbers. But this doesn't always work, and some index are falsely flagged. This problem is hard to address. The TATR detection model might need fine-tuning, or some heuristic crafted to reject reference lists.

2. In this case, it might work to re-parse the table with the so-called large table assumption. This means that row bboxes are algorithmically generated instead of ML-generated. 
```config = TATRFormatConfig() 
config.large_table_threshold = 0
```

3. That's actually a neat feature of [img2table](https://github.com/xavctn/img2table). I've been meaning to add that feature to gmft for quite some time, but I haven't yet. Ideally I want to add img2table integration with gmft (table transformer's detection with img2table's structure analysis) but that is still TODO. In the mean time, img2table may definitely suit your needs.

4. Probably `large_table_row_overlap_threshold`, `large_table_threshold`, `force_large_table_assumption`. Also, padding and margin (these parameters are passed into `AutoTableFormatter.extract()`) This might not be clear in the documentation, but to tweak parameters, the config option can be passed into the constructor of `TATRTableFormatter` or into `ft.df(config_overrides=config)`.

For v0.2.0 I've been working on a major overhaul on several settings. One of these is a tweak to the padding (using pixels from the pdf instead of blank pixels) which seems to decrease overlap errors.

**Comment by snexus** [comment]
Thank you for the answers, very helpful. Looking forward to v0.2

> That's actually a neat feature of [img2table](https://github.com/xavctn/img2table). I've been meaning to add that feature to gmft for quite some time, but I haven't yet. Ideally I want to add img2table integration with gmft (table transformer's detection with img2table's structure analysis) but that is still TODO. In the mean time, img2table may definitely suit your needs.

Will try this out. Is it comparable in speed with gmft? Wouldn't want to increase the running time by 50% just to get the title of the table. 
Another idea might be to extract adjacent text to the tables (since gmft parses text anyway), using some bbox heuristic, e.g. get a text from the closest bounding box from below or above table.

**Comment by conjuncts** [comment]
Yes - in fact img2table is in fact faster than gmft because it is entirely non-deep. Note that I am not the author of img2table, but I did [try it out](https://colab.research.google.com/drive/1_TD2U0JsaW0SqmuCUv7iSbAyJwvRuq_C) when [comparing](https://docs.google.com/spreadsheets/d/12IhxHZbYF71dPl32PQpF_6pg9e9S8f9W4sTHt-B0KTg) the existing options for table extraction. 

I think that img2table is a very good option:

Strengths
- alignment accuracy
- large tables
- ability to handle multi-indices
- ability to extract table titles is pretty unique among the options
    - For gmft, a heuristic is also what I'm thinking -- maybe even throw in a regex for "Table \d*" to avoid grabbing the subsequent paragraph
- throughput

Weaknesses
- vertical tables
- underlying OCR issues
- tables with a mix of explicit rows (solid lines) and implicit rows can be merged
    - lacks semantic understanding of rows, which is the advantage of deep approaches
- false positive rates
    - Different from gmft/TATR's: img2table picks up on paragraphs, figures and graphs. Like gmft, img2table also struggles with reference lists.
- img2table misses a few tables compared to gmft/TATR

Hence my desire to combine deep detection with img2table integration. But I think with v0.2 I will support many of these features like multi-indices and table titles.

**Comment by snexus** [comment]
This is great, thanks for info and the comparison table.
 I will wait for v0.2 and will do a few tests on img2table meanwhile. Can potentially provide pdfs with problematic tables that I encountered so far, if it helps.

**Comment by conjuncts** [comment]
By the way, a [config guide](https://gmft.readthedocs.io/en/latest/config.html) is available that hopefully summarizes a few of the config options.
